# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d1e75ba6beae06795daad260a04e7f6b44518a0e4e9817e27e42a8b4d1432290ad62bf47e52fd9a810d91e1d09dba6e004fab03a850765692a09b9c9e270ea

test:
  secret_key_base: c1a87b83fa992d5572163b77dd68a445f97ec3ac49ab57580e8b3dceaedde7f9fd9fb4da34ef7625651850c6631e2f5c49d1bacdea18be929c8ed49c2420ab42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
